In [1]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

# Assignment - Hypothesis Testing
This assignment requires more individual learning than previous assignments - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. 

Definitions:
* A _quarter_ is a specific three month period, Q1 is January through March, Q2 is April through June, Q3 is July through September, Q4 is October through December.
* A _recession_ is defined as starting with two consecutive quarters of GDP decline, and ending with two consecutive quarters of GDP growth.
* A _recession bottom_ is the quarter within a recession which had the lowest GDP.
* A _university town_ is a city which has a high percentage of university students compared to the total population of the city.

**Hypothesis**: University towns have their mean housing prices less effected by recessions. Run a t-test to compare the ratio of the mean price of houses in university towns the quarter before the recession starts compared to the recession bottom. (`price_ratio=quarter_before_recession/recession_bottom`)

The following data files are available for this assignment:
* From the [Zillow research data site](http://www.zillow.com/research/data/) there is housing data for the United States. In particular the datafile for [all homes at a city level](http://files.zillowstatic.com/research/public/City/City_Zhvi_AllHomes.csv), ```City_Zhvi_AllHomes.csv```, has median home sale prices at a fine grained level.
* From the Wikipedia page on college towns is a list of [university towns in the United States](https://en.wikipedia.org/wiki/List_of_college_towns#College_towns_in_the_United_States) which has been copy and pasted into the file ```university_towns.txt```.
* From Bureau of Economic Analysis, US Department of Commerce, the [GDP over time](http://www.bea.gov/national/index.htm#gdp) of the United States in current dollars (use the chained value in 2009 dollars), in quarterly intervals, in the file ```gdplev.xls```. For this assignment, only look at GDP data from the first quarter of 2000 onward.

In [2]:
# Use this dictionary to map state names to two letter acronyms
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 'OR': 'Oregon', 'MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 'VT': 'Vermont', 'ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii', 'WI': 'Wisconsin', 'MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 'GU': 'Guam', 'MS': 'Mississippi', 'PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 'SD': 'South Dakota', 'MP': 'Northern Mariana Islands', 'IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut', 'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana', 'KS': 'Kansas', 'NY': 'New York', 'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota', 'VI': 'Virgin Islands', 'NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia', 'ND': 'North Dakota', 'VA': 'Virginia'}

In [34]:
import pandas as pd

def f1(row, data, param):
    if param['state'] == '' or row[0].find('edit') > 0:
        param['state'] = row[0].split('[')[0]
    else:
        town = row[0].split('(')[0].strip()
        data.append([param['state'], town])
        
def get_list_of_university_towns():
    '''Returns a DataFrame of towns and the states they are in from the 
    university_towns.txt list. The format of the DataFrame should be:
    DataFrame( [ ["Michigan", "Ann Arbor"], ["Michigan", "Yipsilanti"] ], 
    columns=["State", "RegionName"]  )
    
    The following cleaning needs to be done:

    1. For "State", removing characters from "[" to the end.
    2. For "RegionName", when applicable, removing every character from " (" to the end.
    3. Depending on how you read the data, you may need to remove newline character '\n'. '''
   #your code here
    pass

data = pd.read_fwf('university_towns.txt', header=None)
row = data.index
param = []
f1(row, data, param)

TypeError: list indices must be integers or slices, not str

In [15]:
data = pd.read_csv(r'City_Zhvi_AllHomes.csv',encoding="ISO-8859-1")
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12901 entries, 0 to 12900
Data columns (total 283 columns):
RegionID      int64
RegionName    object
State         object
Metro         object
CountyName    object
SizeRank      int64
1996-04       float64
1996-05       float64
1996-06       float64
1996-07       float64
1996-08       float64
1996-09       float64
1996-10       float64
1996-11       float64
1996-12       float64
1997-01       float64
1997-02       float64
1997-03       float64
1997-04       float64
1997-05       float64
1997-06       float64
1997-07       float64
1997-08       float64
1997-09       float64
1997-10       float64
1997-11       float64
1997-12       float64
1998-01       float64
1998-02       float64
1998-03       float64
1998-04       float64
1998-05       float64
1998-06       float64
1998-07       float64
1998-08       float64
1998-09       float64
1998-10       float64
1998-11       float64
1998-12       float64
1999-01       float64
1999-02       float64
1999-03       float64
1999-04       float64
1999-05       float64
1999-06       float64
1999-07       float64
1999-08       float64
1999-09       float64
1999-10       float64
1999-11       float64
1999-12       float64
2000-01       float64
2000-02       float64
2000-03       float64
2000-04       float64
2000-05       float64
2000-06       float64
2000-07       float64
2000-08       float64
2000-09       float64
2000-10       float64
2000-11       float64
2000-12       float64
2001-01       float64
2001-02       float64
2001-03       float64
2001-04       float64
2001-05       float64
2001-06       float64
2001-07       float64
2001-08       float64
2001-09       float64
2001-10       float64
2001-11       float64
2001-12       float64
2002-01       float64
2002-02       float64
2002-03       float64
2002-04       float64
2002-05       float64
2002-06       float64
2002-07       float64
2002-08       float64
2002-09       float64
2002-10       float64
2002-11       float64
2002-12       float64
2003-01       float64
2003-02       float64
2003-03       float64
2003-04       float64
2003-05       float64
2003-06       float64
2003-07       float64
2003-08       float64
2003-09       float64
2003-10       float64
2003-11       float64
2003-12       float64
2004-01       float64
2004-02       float64
2004-03       float64
2004-04       float64
2004-05       float64
2004-06       float64
2004-07       float64
2004-08       float64
2004-09       float64
2004-10       float64
2004-11       float64
2004-12       float64
2005-01       float64
2005-02       float64
2005-03       float64
2005-04       float64
2005-05       float64
2005-06       float64
2005-07       float64
2005-08       float64
2005-09       float64
2005-10       float64
2005-11       float64
2005-12       float64
2006-01       float64
2006-02       float64
2006-03       float64
2006-04       float64
2006-05       float64
2006-06       float64
2006-07       float64
2006-08       float64
2006-09       float64
2006-10       float64
2006-11       float64
2006-12       float64
2007-01       float64
2007-02       float64
2007-03       float64
2007-04       float64
2007-05       float64
2007-06       float64
2007-07       float64
2007-08       float64
2007-09       float64
2007-10       float64
2007-11       float64
2007-12       float64
2008-01       float64
2008-02       float64
2008-03       float64
2008-04       float64
2008-05       float64
2008-06       float64
2008-07       float64
2008-08       float64
2008-09       float64
2008-10       float64
2008-11       float64
2008-12       float64
2009-01       float64
2009-02       float64
2009-03       float64
2009-04       float64
2009-05       float64
2009-06       float64
2009-07       float64
2009-08       float64
2009-09       float64
2009-10       float64
2009-11       float64
2009-12       float64
2010-01       float64
2010-02       float64
2010-03       float64
2010-04       float64
2010-05       float64
2010-06       float64
2010-07       float64
2010-08       float64
2010-09       float64
2010-10       float64
2010-11       float64
2010-12       float64
2011-01       float64
2011-02       float64
2011-03       float64
2011-04       float64
2011-05       float64
2011-06       float64
2011-07       float64
2011-08       float64
2011-09       float64
2011-10       float64
2011-11       float64
2011-12       float64
2012-01       float64
2012-02       float64
2012-03       float64
2012-04       float64
2012-05       float64
2012-06       float64
2012-07       float64
2012-08       float64
2012-09       float64
2012-10       float64
2012-11       float64
2012-12       float64
2013-01       float64
2013-02       float64
2013-03       float64
2013-04       float64
2013-05       float64
2013-06       float64
2013-07       float64
2013-08       float64
2013-09       float64
2013-10       float64
2013-11       float64
2013-12       float64
2014-01       float64
2014-02       float64
2014-03       float64
2014-04       float64
2014-05       float64
2014-06       float64
2014-07       float64
2014-08       float64
2014-09       float64
2014-10       float64
2014-11       float64
2014-12       float64
2015-01       float64
2015-02       float64
2015-03       float64
2015-04       float64
2015-05       float64
2015-06       float64
2015-07       int64
2015-08       int64
2015-09       int64
2015-10       int64
2015-11       int64
2015-12       int64
2016-01       int64
2016-02       int64
2016-03       int64
2016-04       int64
2016-05       int64
2016-06       int64
2016-07       int64
2016-08       int64
2016-09       int64
2016-10       int64
2016-11       int64
2016-12       int64
2017-01       int64
2017-02       int64
2017-03       int64
2017-04       int64
2017-05       int64
2017-06       int64
2017-07       int64
2017-08       int64
2017-09       int64
2017-10       int64
2017-11       int64
2017-12       int64
2018-01       int64
2018-02       int64
2018-03       int64
2018-04       int64
2018-05       int64
2018-06       int64
2018-07       int64
2018-08       int64
2018-09       int64
2018-10       int64
2018-11       int64
2018-12       int64
2019-01       int64
2019-02       int64
2019-03       int64
2019-04       int64
dtypes: float64(231), int64(48), object(4)
memory usage: 27.9+ MB

In [0]:
def get_recession_start():
    '''Returns the year and quarter of the recession start time as a 
    string value in a format such as 2005q3'''
    #your code here

In [0]:
def get_recession_end():
    '''Returns the year and quarter of the recession end time as a 
    string value in a format such as 2005q3'''
    #your code here

get_recession_end()

In [0]:
def get_recession_bottom():
    '''Returns the year and quarter of the recession bottom time as a 
    string value in a format such as 2005q3'''
    #your code here

In [0]:
def new_col_names():
    #generating the new coloumns names 
    years = list(range(2000,2017))
    quars = ['q1','q2','q3','q4']
    quar_years = []
    for i in years:
        for x in quars:
            quar_years.append((str(i)+x))
    return quar_years[:67]

def convert_housing_data_to_quarters():
    '''Converts the housing data to quarters and returns it as mean 
    values in a dataframe. This dataframe should be a dataframe with
    columns for 2000q1 through 2016q3, and should have a multi-index
    in the shape of ["State","RegionName"].
    
    Note: Quarters are defined in the assignment description, they are
    not arbitrary three month periods.
    
    The resulting dataframe should have 67 columns, and 10,730 rows.
    '''
    #your code here

In [0]:
def run_ttest():
    '''First creates new data showing the decline or growth of housing prices
    between the recession start and the recession bottom. Then runs a ttest
    comparing the university town values to the non-university towns values, 
    return whether the alternative hypothesis (that the two groups are the same)
    is true or not as well as the p-value of the confidence. 
    
    Return the tuple (different, p, better) where different=True if the t-test is
    True at a p<0.01 (we reject the null hypothesis), or different=False if 
    otherwise (we cannot reject the null hypothesis). The variable p should
    be equal to the exact p value returned from scipy.stats.ttest_ind(). The
    value for better should be either "university town" or "non-university town"
    depending on which has a lower mean price ratio (which is equivilent to a
    reduced market loss).'''
  #your code here