**OOP: Calculate median household savings**.

In a csv file you are given the following details for every person.
  * household-id  - a unique number for each household
  * age                  - an integer
  * gender            - 'm' or 'f'
  * profession     - one of the ['Employed', 'Politician', 'Business', 'Not earning']
 
4 - 21 year olds are students and spend (1000 php + 10 * age) as fees.

Average expenditure for people other than that on education is as follows 
* For men - 500 php + 5 * age for men
* For women - 400 php + 7 * age for women

Amount people earn is as follows
* Employees - 1500 * age for age =< 60,  5000 php if age > 60
* Politicians - 2500 * (age - 20)
* Businessmen - 2000 * number-of-people-in-household-with-age > 18

Savings per household is: total income - total expenditure - expense on education.

In [0]:
# Define a class Person which takes house-id, age and gender as constructor arguments.
# Define a method income() and return-zero. By default, people do not earn.
# Define a method expenditure() and return value as explained above.
class Person:
  # IMPLEMENT HERE
  def __init__(self, house_id, age, gender):
    self.house_id = house_id
    self.age = age
    self.gender = gender
    
  def income(self):
    return 0

  def expenditure(self):
    if self.age <= 21:
      print(1000 + 10*self.age)
    else:
      if self.gender == 'f':
        print(400 + 7*self.age)
      else:
        print(500 + 5*self.age)


# Next define a class Household which taked household id as the argument and let
# it have a property members_list which is a list of Person instances.
# Implement a method num_adults() and return the number of adults > 18 years.
# Implement a method savings() which totals over member's income and expenditure.
class HouseHold:
  self.members_list = []
  
  # IMPLEMENT HERE
  def num_adults(self):
    return self.members_list[self.age > 18]

  def savings(self):
    return total income - total expenditure - expense on education
    

# Define following sub-classes of Person - BusinessPerson, Employed, Politician
# and Student.
# Implement income() of BusinessPerson, Employed, Politician as explained above.
# For Student - you have two options to model education expenditure
#     a. Let income() return a negative amount.
#     b. Override expenditure() and return super.expenditure() + education-expense.
#
# Now since income of Business people depends on the number of adumts in the
# household, the income method should take an argument - an instance of household.
# Go back and change the method signature to make income() take an argument, and
# change HouseHold.savings() method to pass 'self' as an argument to Person.income()
#
# (Note: It is also possible to do this without changing method signature, for that
# you will have to change the constructor argument of BusinessPerson to take the
# Household instance as a member attribute. This means one will have to instanciate
# Household before instanciating BusinessPerson).

class BusinessPerson(Person):
  def __init__(self):
    Person.__init__(self)
    for self.age > 18:
      x = len(self.members_list[self.age])
      print(2000 * x)

class Employed(Person):
  def __init__(self):
    Person.__init__(self)
    if self.age <= 60:
      print(sum(2500 * self.members_list[self.age]))
    else:
      print(sum(5000 * self.members_list[self.age]))
        
class Politician(Person):
  def __init__(self):
    Person.__init__(self)
    print(2500 * (self.age - 20))
        
class Student(Person):
  def __init__(self):
    Person.__init__(self)
    print(-1*self.income())


# IMPLEMENT HERE


# Let us create a map (a dictionary called a map datastructure) of
# household-id -> Household.

household_by_id = {}

# Read the csv data file
# For every line read, check if HouseHold already exists in the dictionary.
# If not, create a HouseHold instance and put it in the dictionary, else use the
# existing one.

# IMPLEMENT HERE
import pandas as pd
import numpy as np
data = pd.read_csv(r'/home/data/household.csv')




# Create a correct person instance depending on the profession.

# IMPLEMENT HERE


household_savings = []
# Iterate through each household, computing its savings and adding it to the array.

# IMPLEMENT HERE

# Sort the array and find the median.

# IMPLEMENT HERE

**SQL: Find information from Argentina's real-estate listings.**

There are two Tables in the 'eskwelabs' SQL database which we are going to use for this assignment. You can access these tables by opening a terminal on notebooks.eskwelabs.com and connecting to the database using `/usr/bin/psql -d eskwelabs -U <username>`

Password is '123'

Usernames are (pick the one corresponding to your email id) -

"albertyumol",
"angeliemaglasang",
"anuragadarsh",
"ariannetorres98",
"asya",
"beomiguel",
"dianneashtan",
"elissamaecabal",
"ginoangelomercado",
"henrylaynesa",
"jeffdiala",
"jefrenabalos",
"joaovalenciano",
"johngabrieldaos",
"johnnyong963",
"karendmacuna",
"kevinroelacadin",
"khagonia",
"lexxeltanganco",
"lorenzostamaria",
"luckymores",
"mjjimenez87",
"mposorio",
"rjain09",
"ronmdn",
"rosielvillareal",
"willordcapulong"


  The two tables are -

`property_201501` and `property_201701`
  
  
  Table fields are:
  
 ```
id	STRING	NULLABLE	
created_on	DATE	NULLABLE	
operation	STRING	NULLABLE	
property_type	STRING	NULLABLE	
place_name	STRING	NULLABLE	
place_with_parent_names	STRING	NULLABLE	
country_name	STRING	NULLABLE	
state_name	STRING	NULLABLE	
geonames_id	INTEGER	NULLABLE	
lat_lon	STRING	NULLABLE	
lat	FLOAT	NULLABLE	
lon	FLOAT	NULLABLE	
price	FLOAT	NULLABLE	
currency	STRING	NULLABLE	
price_aprox_local_currency	FLOAT	NULLABLE	
price_aprox_usd	FLOAT	NULLABLE	
surface_total_in_m2	INTEGER	NULLABLE	
surface_covered_in_m2	INTEGER	NULLABLE	
price_usd_per_m2	FLOAT	NULLABLE	
price_per_m2	FLOAT	NULLABLE	
floor	INTEGER	NULLABLE	
rooms	INTEGER	NULLABLE	
expenses	INTEGER	NULLABLE	
properati_url	STRING	NULLABLE	
description	STRING	NULLABLE	
title	STRING	NULLABLE	
image_thumbnail	STRING	NULLABLE
```


  
  
  Your task is to find the following information from these two tables -
  
  
 Work with property listings table for 201501
 
 Query format:
 
 
 `SELECT <field1>, <field2>,.. FROM <table1> WHERE <condition> ORDER BY <field> LIMIT <number>`
 
**Always user LIMIT clause to save resources if possible**

1. Select any 10 properties from the table.
2. Select any 10 properties from the table with property_type 'house'.
3. Find the most expensive house in CÃ³rdoba.
4. How many apartment listings were created on 2015-01-01?
5. Which is the southern most property available?
6. Can you find out which date has the highest number of created listings?


Now let us work with joins between `property_201501` and `property_201701`.

`SELECT <field1> FROM <table1> t1 INNER JOIN <table2> t2 on t1.x = t2.y`

t1 and t2 are aliases for table1 and table2 respectively.

1. Select any 10 listings common between these two tables.
2. How many listings are common in two tables?
3. How many listings prices have gone up?
4. Which are the top 10 listings in terms of rent increase?